# Generated by Django 5.1.1 on 2024-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=255)),
                ('user_password', models.TextField()),
                ('user_compte_id', models.IntegerField(unique=True)),
                ('user_mail', models.EmailField(max_length=255)),
                ('user_date_new', models.DateTimeField(auto_now_add=True)),
                ('user_date_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
