# Generated by Django 5.1.1 on 2024-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_objet', models.CharField(choices=[('potion', 'Potion'), ('plante', 'Plante'), ('arme', 'Arme'), ('cle', 'Clé'), ('armure', "Pièce d'armure")], max_length=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
